# write a program to input eight number from the user and display all the union numbers(once)

s = set()
n = input("Enter number:")
s.add(int(n))
n = input("Enter number:")
s.add(int(n))
n = input("Enter number:")
s.add(int(n))
n = input("Enter number:")
s.add(int(n))
n = input("Enter number:")
s.add(int(n))
n = input("Enter number:")
s.add(int(n))
n = input("Enter number:")
s.add(int(n))

print(s)